### ISSUE TITLE
IOS: Symbol not found: _grpcsharp_redirect_log

### ISSUE THREAD

**Issue by Rurouni** [neuecc/MagicOnion#20]
Hi,
I have tried to run it in IOS and it fails with 
`dyld: lazy symbol binding failed: Symbol not found: _grpcsharp_redirect_log`

in that function:
```
// System.Void Grpc.Core.Internal.NativeMethods/Delegates/grpcsharp_redirect_log_delegate::Invoke(Grpc.Core.Internal.GprLogDelegate)
extern "C"  void grpcsharp_redirect_log_delegate_Invoke_m3963642216 (grpcsharp_redirect_log_delegate_t2162057115 * __this, GprLogDelegate_t430330606 * ___callback0, const MethodInfo* method)
{
	if(__this->get_prev_9() != NULL)
	{
		grpcsharp_redirect_log_delegate_Invoke_m3963642216((grpcsharp_redirect_log_delegate_t2162057115 *)__this->get_prev_9(),___callback0, method);
	}
	il2cpp_codegen_raise_execution_engine_exception_if_method_is_not_found((MethodInfo*)(__this->get_method_3().get_m_value_0()));
	bool ___methodIsStatic = MethodIsStatic((MethodInfo*)(__this->get_method_3().get_m_value_0()));
	if (__this->get_m_target_2() != NULL && ___methodIsStatic)
	{
		typedef void (*FunctionPointerType) (Il2CppObject *, void* __this, GprLogDelegate_t430330606 * ___callback0, const MethodInfo* method);
		((FunctionPointerType)__this->get_method_ptr_0())(NULL,__this->get_m_target_2(),___callback0,(MethodInfo*)(__this->get_method_3().get_m_value_0()));
	}
	else if (__this->get_m_target_2() != NULL || ___methodIsStatic)
	{
		typedef void (*FunctionPointerType) (void* __this, GprLogDelegate_t430330606 * ___callback0, const MethodInfo* method);
		((FunctionPointerType)__this->get_method_ptr_0())(__this->get_m_target_2(),___callback0,(MethodInfo*)(__this->get_method_3().get_m_value_0()));
	}
	else
	{
		typedef void (*FunctionPointerType) (void* __this, const MethodInfo* method);
		((FunctionPointerType)__this->get_method_ptr_0())(___callback0,(MethodInfo*)(__this->get_method_3().get_m_value_0()));
	}
}
```

I wonder if I hasn't done some magic configuration on the Native dlls or something,  but `gRPC/Native/iOS/libgrpc_csharp_ext.a` and others there are configured to be included in IOS build...

**Comment by neuecc** [comment]
I do not know the solution to the problem.
googled:"dyld: lazy symbol binding failed" find some (same?) faq but I can not understand whether it is suitable or not.

**Comment by neuecc** [comment]
Yes, it is running on iOS (It is being built everyday in our game under development now)
As I update to 1.3 soon, can you see it at that time?
The custom code of gRPC is here.
https://github.com/grani/gRPC/tree/UnityClient
We've modified some of issue, including freeze of Unity Editor.

**Comment by Rurouni** [comment]
You use il2cpp backend for IOS right?

> As I update to 1.3 soon, can you see it at that time?

Do you mean that you are in the progress of updating to 1.2 grpc?

**Comment by neuecc** [comment]
Yes, I use IL2CPP backend only.

Ah, sorry, '1.2'.
Yes, I plan to upgrade this week or next week.

**Comment by Rurouni** [comment]
Cheers, that would be great. In the meantime I will try to build native dlls manually from your UnityClient branch

**Comment by Rurouni** [comment]
I have tried running unaltered latest MagicOnion and I can't even build it for IOS/IL2CPP/Simulator
```
IL2CPP error for method 'System.Int32 MessagePack.LZ4.LZ4Codec::Encode32(System.Byte*,System.Byte*,System.Int32,System.Int32)' in LZ4Codec.Unsafe.cs:83
Additional information: Exception of type 'System.Exception' was thrown.
```
I have then tried mono backend instead of il2cpp  and it builds and deploys to simulator but then any access to NativeMethods yields EntrypointNotFoundException that looks like same root cause as in my original case with il2cpp

I am also struggling to build native dependencies for IOS. When I am building grpc from the branch you have given I can see libs like libgrpc.a or libboringssl.a and some more but not libgrpc_csharp_ext.a or libgRPC-Core.a. Can you advise please on how you build them?

**Comment by neuecc** [comment]
Oh, sorry, I've fixed MessagePack for C# + IL2CPP compile issue on MessagePack repository
but it is not yet moved on MagicOnion repository.

// old, MagicOnion
https://github.com/neuecc/MagicOnion/tree/master/src/MagicOnion.Client.Unity/Assets/Scripts/MessagePack/LZ4/Codec

// new, MessagePack
https://github.com/neuecc/MessagePack-CSharp/tree/master/src/MessagePack/LZ4/Codec

**Comment by neuecc** [comment]
Environment:
* Mac (Sierra 10.12)
* Xcode (8.1)
* CocoaPods (1.1.1)

build shell.
https://github.com/grani/grpc/blob/UnityClient/build_grpc_cshap_ext.sh

our ci command:
```
build_type="Debug"
# build_type="Release"
output_dir="./out/${build_type}"

chmod +x ./build_grpc_cshap_ext.sh
./build_grpc_cshap_ext.sh "$output_dir" $build_type
```

**Comment by neuecc** [comment]
I've uploaded v0.4.0 and its .unitypackage on releases page.

**Comment by Rurouni** [comment]
I have upgraded to latest. 1.2 works perfectly. 👍 
Though I still can't figure out how to run it in editor on mac. I can see there is now Native/Mac folder that contains some .bundle_ file  but it doesn't look like object library file and when I run in editor it still complains that it can't find entrypoints for native methods. Should it work out of the box or do I need some additional configuration?

**Comment by neuecc** [comment]
Sorry, `.bundle_` is `.bundle` file, please rename it and is it work?
Bundle was recognized as a folder and could not be packaged, it was included as bundle_.
I've take it from NuGet, `1.2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib` and renamed.
I am not familiar with plugins in Mac Editor, so I can not confirm whether it actually works.

**Comment by Rurouni** [comment]
It started to work as soon as I renamed to .bundle. 
Thank you for your help!
